NineGagBundle\Entity\Score:
    type: entity
    table: null
    repositoryClass: NineGagBundle\Repository\ScoreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: integer
    manyToOne:
        post:
          targetEntity: Post
          inversedBy: scores
          joinColumn:
            name: post_id
            referencedColumnName: id
        user:
          targetEntity: User
          inversedBy: scores
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
