NineGagBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: NineGagBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '20'
            unique: true
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
